# my-python-examples task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: go

inputs:
- name: concoursegit

outputs:
- name: my-python-examples-updated

run:
  path: concoursegit/scripts/readme.sh