---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "{{kubernetes-version}}"

resources:
- name: image
  type: registry-image
  icon: docker
  source:
    repository: hopetembhum/test1
    tag: "latest"
    username: hopetembhum
    password: 123456789

- name: concoursegit
  type: git
  icon: github
  source:
    uri: https://github.com/Tembhum/concoursedemo.git
    branch: master

- name: kubernetes-cluster
  type: kubernetes
  icon: kubernetes
  source:
    insecure_skip_tls_verify: {{kubernetes-skip-tls-verification}}
    kubeconfig: {{kubernetes-config}}
    context: {{kubernetes-context}}
    namespace: {{kubernetes-namespace}}

jobs:
- name: build-and-push
  plan:
  - get: concoursegit
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/vito/oci-build-task
          repository: vito/oci-build-task
      inputs:
      - name: concoursegit
      outputs:
      - name: image
      params:
        CONTEXT: concoursegit/
      run:
        path: build
  - put: image
    params:
      image: image/image.tar

  - name: deploy-latest-container-image
    plan:
    - get: container-image
      trigger: true
      params:
        skip_download: true
    - put: kubernetes-cluster
      params:
        kubectl: |
          set image deployment ((kubernetes-deployment)) ((kubernetes-container))=$(cat container-image/repository)@$(cat container-image/digest)
        wait_until_ready: {{kubernetes-wait-until-ready}}
